spring:
  application:
    name: chapter-09-sorting-paging
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq_demo
    username: postgres
    password: postgres
  jooq:
    sql-dialect: Postgres
