spring:
  application:
    name: chapter-18-jpa-jooq
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
